2019-09-02 09:23:09,005 ERROR: Exception on /login [GET] [in c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm 2018.2.4\python°à\blog\app\routes.py", line 52, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm 2018.2.4\python°à\blog\app\templates\base.html", line 59, in template
    {% endblock %}
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "D:\PyCharm 2018.2.4\python°à\blog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm 2018.2.4\python°à\blog\app\templates\base.html", line 59, in template
    {% endblock %}
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "c:\users\kxh\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
